sector:
  plane: 
    label: Aviation
    unit: cEUR/PAX/km
  ship:
    label: Maritime transport
    unit: EUR/MWh
  steel: 
    label: Primary steel
    unit: EUR/t<sub>hot rolled coil</sub>
  chem: 
    label: Chemical feedstocks
    unit: EUR/t<sub>olefin</sub>
  cement: 
    label: Cement
    unit: EUR/t<sub>clinker</sub>

case:
  normal:
    label: '<b>No conditions</b>'
  ccu:
    label: '<b>CCU coupling:</b> CCU utilization requires a source (cement or steel).'
  comp:
    label: '<b>Climate neutrality:</b> Full climate neutrality (compensation only for residual emissions).<br>CCU coordination is also required.'

cost_types:
  capex:
    label: Annualised CAPEX
    colour: '#bde0fe'
  opex:
    label: OPEX(fixed)
    colour: '#bde0fe'
  other costs:
    label: Other CAPEX or OPEX
    colour: '#bde0fe'
  fossilJ:
    label: Fossil jet fuel
    colour: '#31393C'
  fossilccoal:
    label: Fossil coking coal
    colour: '#31393C'
  fossilpci:
    label: Fossil PCI coal
    colour: '#31393C'
  fossilng:
    label: Fossil natural gas
    colour: '#31393C'
  fossilnaphta:
    label: Fossil naphtha
    colour: '#31393C'
  fossilcoal:
    label: Fossil bituminous coal
    colour: '#31393C'
  fossilhfo:
    label: Fossil heavy fuel oil
    colour: '#31393C'
  ironore:
    label: Iron ore
    colour: '#b069db'
  scrap:
    label: Scrap
    colour: '#b069db'
  elec:
    label: Electricity
    colour: '#e6af2e'
  heat:
    label: Low temperature heat
    colour: '#7c1f8a'
  h2:
    label: Green H<sub>2</sub>
    colour: '#FCE762'
  nh3:
    label: Green NH<sub>3</sub>
    colour: '#FCE762'
  lh2:
    label: Liquified green H<sub>2</sub>
    colour: '#FCE762'
  co2 tax:
    label: CO<sub>2</sub> tax
    colour: '#aaaaaa'
  co2:
    label: CO<sub>2</sub> (non-fossil)
    colour: '#23CE6B'
  co2ccu:
    label: CO<sub>2</sub> (from a<br> fossil industrial point source)
    colour: '#8E9AAF'
  ch3oh:
    label: Syn-methanol
    colour: '#FEB380'
  ch3ohccu:
    label: Syn-methanol (using fossil CO<sub>2</sub> from CCU)
    colour: '#8E9AAF'
  MtJ:
    label: Syn-jet fuel (methanol route)
    colour: '#FEB380'
  MtJccu:
    label: Syn-jet fuel (methanol route, using fossil CO<sub>2</sub> from CCU)
    colour: '#8E9AAF'
  co2 transport and storage:
    label: CO<sub>2</sub> transport and storage
    colour: '#3083DC'
  cost:
    label: Cost (source available from paper supplementary)
    colour: '#31393C'
  NA:
    label: None
    colour: '#bde0fe'


fossils:
  fossilcoal:
    label: Bituminous coal
    unit: EUR/MWh
  fossilccoal:
    label: Coking coal
    unit: EUR/t
  fossilpci:
    label: PCI coal
    unit: EUR/t
  fossilng:
    label: Natural gas
    unit: EUR/MWh
  fossilnaphta:
    label: Naphtha
    unit: EUR/t
  fossilhfo:
    label: Heavy fuel oil
    unit: EUR/MWh
  fossilJ:
    label: Jet fuel
    unit: EUR/MWh
  fossildiesel:
    label: Diesel
    unit: EUR/MWh
  fossilch3oh:
    label: Methanol
    unit: EUR/MWh