figures:
  fig3:
    name: Fig. 3
    title: Abatement cost comparison for the HTE sectors.
    desc:
      'Sectoral abatement costs for the five HTE sectors.'
    display:
    - ''
    size:
      print:
        width: 180.0  # unit mm
        height: 80.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 600.0  # unit px
config:
  xaxis_title: Technologies
  yaxis_title: Abatement cost (EUR/tCO2)
