figures:
  fig1:
    name: Fig. 1
    title: Levelized cost breakdown for the fuels considered in this work.
    desc:
      Fuel levelized cost components obtained from the techno-economic analysis. Figure 1-a) shows the reference fossil fuel costs used.
      Figure 1-b) shows the cost of the synfuels considered in this work (both DAC based and CCU based).
    display:
    - ''
    - 'advanced'
    size:
      print:
        width: 180.0  # unit mm
        height: 80.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 600.0  # unit px
config:
  xaxis_title: Technologies
  yaxis_title: Cost components
