figures:
  fig4:
    name: Fig. 4
    title: 'Mitigation landscape for the HTE sectors'
    desc:
      'Mitigation landscape: the most cost-effective mitigation option, in terms of abatement costs, is shown for any given set of low-emission hydrogen and non-fossil CO2 cost.'
    display:
    - 'advanced'
    size:
      print:
        width: 180.0  # unit mm
        height: 80.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 500.0  # unit px
config:
  title: '<b>Case:</b> '
  xaxis_title: Non-fossil CO2 cost
  yaxis_title: Low-emission H2 cost
  colorbar_title: Abatement options