figures:
  fig1:
    name: Fig. 1
    title: Stacked bar plot.
    desc:
      'Detailed description bla bla bla.'
    display:
    - ''
    - 'advanced'
    size:
      print:
        width: 180.0  # unit mm
        height: 80.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 600.0  # unit px
config:
  xaxis_title: Technologies
  yaxis_title: Cost components
