figures:
  fig2:
    name: Fig. 2
    title: Levelized cost breakdown for the HTE sectors.
    desc:
      'Sectoral levelized cost components for the five HTE sectors.'
    display:
    - ''
    - 'advanced'
    size:
      print:
        width: 180.0  # unit mm
        height: 80.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 600.0  # unit px
config:
  xaxis_title: Technologies
  yaxis_title: Cost components
